print("\n Menu to for managing tasks/to-do-list")
print("1. Add a task")
print("2. See tasks")
print("3. Update a task")
print("4. Mark task as completed")
print("5. Delete complete task(s)")
print("6. Exit")
